data<-read.csv("C:\\Users\\dell\\Desktop\\akshay\\DataScience\\datasciencecoursera\\hw1_data.csv",header=T)
names(data)
nrow(data)
miss<-is.na(data[,"ozone"])
sum(miss)
mean(data[,"Ozone"],na.rm=TRUE)
colnames(data)
x<-subset(data,Ozone>31 & Temp>91,select = Solar.R)
apply(x, 2,mean)
y<-subset(data,Month==6,select=Temp)
apply(y,2,mean)
z<-subset(data,Month==5 & !is.na(Ozone),select=Ozone)
apply(z,2,max)
head(data,2)
tail(data,2)
data[47,1]
miss<-is.na(data[,"Ozone"])
sum(miss)
mean(data[,"Ozone"],na.rm=T)
x<-subset(data,Ozone>31 & Temp>90,select = Solar.R)
apply(x, 2,mean)
y<-subset(data,Month==6,select = Temp)
apply(y, 2,mean)
z<-subset(data,Month==5 & !is.na(Ozone),select=Ozone)
apply(z,2,max)

